import type { Metadata } from "next";
import { Quicksand } from "next/font/google";
import "./globals.css";
import Nav from "@/components/Nav";
import Footer from "@/components/Footer";

const quicksand = Quicksand({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: {
    absolute: "",
    default: "Home | >_basu",
    template: "%s | >_basu",
  },
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={quicksand.className}>
        <div className="bg-gradient-conic">
          <Nav />
          {children}
          <Footer />
        </div>
      </body>
    </html>
  );
}
